apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: publish-role
 namespace: rh-ecosystem-tenant 
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releases
  - releaseplans
  - snapshots
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: publish-rolebinding
 namespace: rh-ecosystem-tenant
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: publish-role
subjects:
- kind: ServiceAccount
  name: appstudio-pipeline 
  namespace: rh-ecosystem-tenant
